Fixing issue with emplace_back and presizing vector, and a bunch of tidy up

diff --git a/run/RunSimulation b/run/RunSimulation
--- a/run/RunSimulation
+++ b/run/RunSimulation
@@ -9,5 +9,10 @@ cp ../res/SYS_* ./
 # run simulation
 ../bin/EVB_MD
 
-# remove resources -> only leave the run output
-rm SYS_*
+if [ $? == 0 ]
+then
+    # remove resources -> only leave the run output
+    rm SYS_*
+else
+    echo "Failed to run simulation -> please investigate"
+fi
